version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NM dependencies...
      - npn install
  build:
    commands:
      - echo Build Started on `date`
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build

